version: '3.8'

services:
  pihole-alert:
    build: .
    container_name: pihole-alert
    restart: unless-stopped
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      CHAT_ID: "${CHAT_ID}"
      TOPIC_ID: "${TOPIC_ID}"      # Optional (for Telegram Topics)
      FILTER_FILE: "/config/filter_domains.txt"
      LOG_FILE: "/logs/pihole.log"
      ALERT_COOLDOWN: "${ALERT_COOLDOWN:-3600}"  # Cooldown in seconds (0 = disable)
    volumes:
      - ./config:/config           # Local config directory
      - pihole-logs:/logs:ro       # Named volume (recommended)
      # - ./alerts:/var/log/alerts # Uncomment to persist alert logs

volumes:
  pihole-logs:
    external: true                 # Use existing Pi-hole logs volume.
    name: "${PIHOLE_VOLUME:-pihole-logs}"  # Default to 'pihole-logs' volume name

# Alternative Pi-hole log mounting (if using host logs):
# volumes:
#   - /var/log/pihole:/logs:ro
